[keyboard]
name = "Totemist"
product_name = "Totemist"
vendor_id = 0x1D50
product_id = 0x615E
manufacturer = "RMK"
chip = "nrf52840"
# board = "XIAO BLE"

[layout]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, row2col config here is valid ONLY when you're using cloud compilation.
# Checkout doc here: https://rmk.rs/docs/user_guide/faq.html#my-matrix-is-row2col-the-matrix-doesn-t-work
# row2col = true
rows = 8
cols = 5
layers = 4
matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4)         (4,4) (4,3) (4,2) (4,1) (4,0)
(1,0) (1,1) (1,2) (1,3) (1,4)         (5,4) (5,3) (5,2) (5,1) (5,0)
(2,0) (2,1) (2,2) (2,3) (2,4)         (6,4) (6,3) (6,2) (6,1) (6,0)
            (3,2) (3,3) (3,4)         (7,4) (7,3) (7,2)
"""


# ┌─────────────────────────────────────────────────┐
# │ q w e r t y                                     │
# └─────────────────────────────────────────────────┘
# TH behabior with Key/Mod for the row is further defined as *HMR
# ┏━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┓   ┏━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┓
# ┃     Q     ┃     W     ┃     E     ┃     R     ┃     T     ┃   ┃     Y     ┃     U     ┃     I     ┃     O     ┃     P     ┃
# ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫   ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫
# ┃  A/Super  ┃  S/LAlt   ┃  D/LShift ┃  F/LCtrl  ┃     G     ┃   ┃     H     ┃  J/RCtrl  ┃  K/RShift ┃   L/Ralt  ┃   ;/RGui  ┃
# ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫   ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫
# ┃     Z     ┃     X     ┃     C     ┃     V     ┃     B     ┃   ┃     N     ┃     M     ┃     ,     ┃     .     ┃     /     ┃
# ┗━━━━━━━━━━━┻━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫   ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┻━━━━━━━━━━━┛
#                         ┃    CTRL   ┃  TAB/LO   ┃    SPC    ┃   ┃   ENTER   ┃     HI    ┃   BSPC    ┃
#                         ┗━━━━━━━━━━━┻━━━━━━━━━━━┻━━━━━━━━━━━┛   ┗━━━━━━━━━━━┻━━━━━━━━━━━┻━━━━━━━━━━━┛
[[layer]]
name = "qwerty"
keys = """
Q           W           E             R            T                 Y     U            I             O           P
MT(A, LGui) MT(S, LAlt) MT(D, LShift) MT(F, LCtrl) G                 H     MT(J, RCtrl) MT(K, RShift) MT(L, RAlt) MT(Semicolon, RGui)
Z           X           C             V            B                 N     M            Comma         Dot         Slash
                    LCtrl  LT(low, Tab)        Space                 Enter MO(high)     Backspace
"""

# ┌─────────────────────────────────────────────────┐
# │ l o w                                           │
# └─────────────────────────────────────────────────┘
# ┏━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┓   ┏━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┓
# ┃    ESC    ┃ CAPSLOCK  ┃     ↑     ┃           ┃     {     ┃   ┃     }     ┃     7     ┃     8     ┃     9     ┃    =/+    ┃
# ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫   ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫
# ┃   PGUP    ┃     <-    ┃     ↓     ┃     ->    ┃     [     ┃   ┃     ]     ┃     4     ┃     5     ┃     6     ┃     -     ┃ *HMR
# ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫   ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫
# ┃   PGDN    ┃     Cut   ┃    Copy   ┃   Paste   ┃     (     ┃   ┃     )     ┃     1     ┃     2     ┃     3     ┃     *     ┃
# ┗━━━━━━━━━━━┻━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫   ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┻━━━━━━━━━━━┛
#                         ┃   LShift  ┃     ▼     ┃     ▼     ┃   ┃     ▼     ┃    ADJ    ┃     0     ┃
#                         ┗━━━━━━━━━━━┻━━━━━━━━━━━┻━━━━━━━━━━━┛   ┗━━━━━━━━━━━┻━━━━━━━━━━━┻━━━━━━━━━━━┛
#
[[layer]]
name = "low"
keys = """
Escape           CapsLock       Up               No               SHIFTED(lbrc)        SHIFTED(rbrc) 7            8             9           Equal
MT(PageUp, LGui) MT(Left, LAlt) MT(Down, LShift) MT(Right, LCtrl) LeftBracket          RightBracket  MT(4, RCtrl) MT(5, RShift) MT(6, RAlt) MT(Minus, RGui)
PageDown         @cut           @copy            @paste           SHIFTED(Kc9)         SHIFTED(Kc0)  1            2             3           SHIFTED(Kc8)
                                LShift           ______           _____________        ____________  _            0
"""
# ┌─────────────────────────────────────────────────┐
# │ h i g h                                         │
# └─────────────────────────────────────────────────┘
# ┏━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┓   ┏━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┓
# ┃     !     ┃     @     ┃     #     ┃     $     ┃     %     ┃   ┃     ^     ┃     \     ┃     |     ┃           ┃     +    ┃
# ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫   ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫
# ┃     `     ┃           ┃           ┃           ┃     '     ┃   ┃     &     ┃           ┃           ┃           ┃     _     ┃
# ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫   ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫
# ┃     ~     ┃           ┃           ┃           ┃     ;     ┃   ┃     <     ┃     >     ┃           ┃           ┃           ┃
# ┗━━━━━━━━━━━┻━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫   ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┻━━━━━━━━━━━┛
#                         ┃     ▼     ┃    ADJ    ┃     ▼     ┃   ┃     ▼     ┃     ▼     ┃     ▼     ┃
#                         ┗━━━━━━━━━━━┻━━━━━━━━━━━┻━━━━━━━━━━━┛   ┗━━━━━━━━━━━┻━━━━━━━━━━━┻━━━━━━━━━━━┛
[[layer]]
name = "high"
keys = """
SHIFTED(1)     SHIFTED(2) NonusHash  SHIFTED(4) SHIFTED(5)                    SHIFTED(6)     NonusBackslash SHIFTED(NonusBackslash) No SHIFTED(Equal)
Grave          No         No         No         Quote                         SHIFTED(7)     No             No                      No SHIFTED(Minus)
SHIFTED(Grave) No         No         No         Semicolon                     SHIFTED(Comma) SHIFTED(Dot)   No                      No No
                          __         __         _________                     __________ __________     __
"""
# ┌─────────────────────────────────────────────────┐
# │ a d j u s t                   * not implemented │
# └─────────────────────────────────────────────────┘
# ┏━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┓   ┏━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┓
# ┃  RESET*   ┃ BT CLR*   ┃   VolUp   ┃           ┃           ┃   ┃           ┃     F7    ┃     F8    ┃     F9    ┃    F12    ┃
# ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫   ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫
# ┃  BOOTLD   ┃ BT NXT*   ┃   VolDn   ┃           ┃           ┃   ┃           ┃     F4    ┃     F5    ┃     F6    ┃    F11    ┃
# ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫   ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫
# ┃           ┃ BT PRV*   ┃   Mute    ┃           ┃           ┃   ┃           ┃     F1    ┃     F2    ┃     F3    ┃    F10    ┃
# ┗━━━━━━━━━━━┻━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┫   ┣━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━┻━━━━━━━━━━━┛
#                         ┃     ▼     ┃     ▼     ┃     ▼     ┃   ┃     ▼     ┃     ▼     ┃     ▼     ┃
#                         ┗━━━━━━━━━━━┻━━━━━━━━━━━┻━━━━━━━━━━━┛   ┗━━━━━━━━━━━┻━━━━━━━━━━━┻━━━━━━━━━━━┛

[[layer]]
name = "adjust"
keys = """
No         No AudioVolUp   No No      No F7 F8 F9 F12
Bootloader No AudioVolDown No No      No F4 F5 F6 F11
No         No AudioMute    No No      No F1 F2 F3 F10
              ____________ __ __      __ __ __
"""


[aliases]
cut = "WM(X, LCtrl)"
copy = "WM(C, LCtrl)"
paste = "WM(V, LCtrl)"

[behavior.tri_layer]
upper = 2
lower = 1
adjust = 3

[ble]
enabled = true
battery_adc_pin = "vddh"

[storage]
enabled = true
clear_storage = false

[behavior]
tap_hold = { enable_hrm = true, permissive_hold = true, chordal_hold = true, prior_idle_time = "120ms", hold_timeout = "250ms" }

[split]
connection = "ble"

[split.central]
rows = 4
cols = 5
row_offset = 0
col_offset = 0

[split.central.matrix]
input_pins = ["P0_02", "P0_03", "P0_28", "P0_29"]
output_pins = ["P0_04", "P0_05", "P1_15", "P1_14", "P1_13"]

[[split.peripheral]]
rows = 4
cols = 5
row_offset = 4
col_offset = 0

[split.peripheral.matrix]
input_pins = ["P0_02", "P0_03", "P0_28", "P0_29"]
output_pins = ["P0_04", "P0_05", "P1_15", "P1_14", "P1_13"]
